# Generated by Django 3.2 on 2021-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20211112_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='mailchimp_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
