# Generated by Django 3.2 on 2021-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20211115_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='mailchimp_subscribed',
            field=models.BooleanField(null=True),
        ),
    ]
