# Generated by Django 3.2 on 2021-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20211116_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermessage',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='newslettertype',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='subtitle',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='NewsLetterTrigger',
        ),
    ]
