# Generated by Django 3.2 on 2021-11-16 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20211116_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='title',
        ),
        migrations.AddField(
            model_name='customermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
