# Generated by Django 3.2 on 2021-11-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20211116_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='greeting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
