# Generated by Django 3.2 on 2021-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_brand_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
