# Generated by Django 3.2 on 2021-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20211009_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolCustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_by_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_by_percentage', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('discount_by_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_by_percentage', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
