# Generated by Django 3.2 on 2021-10-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_coolcustomerdiscount_specialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='discount_by_amount',
        ),
    ]
