# Generated by Django 3.2 on 2021-10-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_percentage'),
        ('marketing', '0008_auto_20211016_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
    ]
