# Generated by Django 3.2 on 2021-10-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20211011_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='purchase_price_total',
            new_name='product_purchase_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_purchase_price_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_discount',
        ),
    ]
