# Generated by Django 3.2 on 2021-10-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211013_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='price_subtotal',
            new_name='product_price',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='price_total',
        ),
        migrations.AddField(
            model_name='cart',
            name='shipment_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
