# Generated by Django 3.2 on 2021-10-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('shipment_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('free_shipment_purchase_amount_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
        ),
    ]
