# Generated by Django 3.2 on 2021-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shipmentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentmethod',
            old_name='free_shipment_purchase_amount_limit',
            new_name='free_shipment_limit',
        ),
        migrations.AddField(
            model_name='shipmentmethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
