# Generated by Django 3.2 on 2021-11-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address_final',
            new_name='order_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_final',
        ),
    ]
