# Generated by Django 3.2 on 2021-11-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211104_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
